[ids]
1a2c
41e4

[aliases]
capslock=esc
esc=`

6=leftmouse
7=rightmouse
8=6
9=7
0=8
-=9
==0
backspace='

y==
u=y
i=u
o=i
p=o
[=p
]=backspace

h=-
j=h
k=j
l=k
;=l
'=;

b=,
n=.
m=b
,=n
.=m

left=rightcontrol
down=rightcontrol

[main]

space=overloadt2(spacefn, space, 200)

esc=overloadt2(meta, esc, 200)
enter=overloadt2(meta, enter, 200)

leftalt=overloadt2(alt, `, 200)

leftshift=overloadt2(shift, [, 200)
rightshift=overloadt2(shift, ], 200)

z= overloadt2(control, z, 200)
/= overloadt2(control, /, 200)

;= overloadt2(mouseless, ;, 200)

[spacefn]
i=up
k=down
j=left
l=right

u=home
o=end
y=pageup
h=pagedown

backspace=delete
g=toggle(mouseless)

w=1
e=2
r=3
s=4
d=5
f=6
z=7
x=8
c=9
v=0

1=f1
2=f2
3=f3
4=f4
5=f5
6=f6
7=f7
8=f8
9=f9
0=f10
'=f11
\=f12

[mouseless]
i=f13
k=f14
j=f15
l=f16

y=f21
h=f22
u=f23
o=f24

s=f17
f=leftmouse
d=rightmouse
c=compose

enter=clearm(leftmouse)
esc=clear()
