[ids]
0001

[aliases]

esc=leftmouse
8=6
9=7
0=8
-=9
==0
backspace='

y==
u=y
i=u
o=i
p=o
[=p
]=backspace

h=-
j=h
k=j
l=k
;=l
'=;

b=,
n=.
m=b
,=n
.=m

[main]
space=overloadt2(control, space, 200)

capslock=overloadt2(nav, esc, 200)
enter=overloadt2(nav, enter, 200)

leftshift=overloadt2(shift, [, 200)
rightshift=overloadt2(shift, ], 200)

[nav:M]
i=up
k=down
j=left
l=right
u=home
o=end
y=pageup
h=pagedown

