# 本机不需要的包（base-system / linux-base 依赖用 ignore 挡掉后再卸）
# 固件保留：intel-ucode、linux-firmware-intel、linux-firmware-network、sof-firmware
ignorepkg=linux-firmware-amd
ignorepkg=linux-firmware-nvidia
ignorepkg=linux-firmware-broadcom
ignorepkg=wifi-firmware
ignorepkg=ipw2100-firmware
ignorepkg=ipw2200-firmware
ignorepkg=zd1211-firmware
ignorepkg=alsa-firmware
# 文件系统工具（根分区是 ext4）
ignorepkg=btrfs-progs
ignorepkg=xfsprogs
ignorepkg=f2fs-tools
# 杂项
ignorepkg=traceroute
ignorepkg=ethtool
