bar:
  location: top
  height: 28
  background: 111719ff
  foreground: c5c8c6ff
  font: "WenQuanYi Micro Hei:size=11"
  spacing: 8
  margin: 8

  left:
    - foreign-toplevel:
        content:
          map:
            conditions:
              activated: {string: {text: "[{app-id}]", foreground: ffffffff}}
              ~activated: {string: {text: "[{app-id}]", foreground: 777777ff}}

  right:
    - battery:
        name: BAT1
        content:
          string: {text: "BAT {capacity}%"}
    - clock:
        content:
          string: {text: "{time}"}
