#!/bin/sh
exec 2>&1
cd /var/lib/text-vault || exit 1
exec chpst -u text-vault envdir /etc/text-vault/env \
  /usr/local/bin/text-vault serve \
  -listen 127.0.0.1:8080 \
  -database /var/lib/text-vault/text-vault.db \
  -secure-cookie=true

